### ISSUE TITLE
A question about the data format

### ISSUE THREAD

**Issue by Shengyuan-Cai** [stephaniebrandl/bci-under-distraction#1]
https://depositonce.tu-berlin.de/handle/11303/10934.2
I would like to ask if there is any raw data in EEG format  before it has been converted to mat format; or is there any data that can be processed with EEGLAB now?

**Comment by stephaniebrandl** [comment]
It should be possible to process the mat files with EEGLAB as well

**Comment by Shengyuan-Cai** [comment]
Thank you
